### ISSUE TITLE
JavaFX missing

### ISSUE THREAD

**Issue by FireFlyerFighter** [amadornes/ModJam5#1]
The mod crashed when I placed down a creative crystal and the log says:
`java.lang.NoClassDefFoundError: com/sun/javafx/geom/Vec3f
	at mod.crystals.client.particle.ParticleType.posVelocityColor(ParticleType.java:61) ~[ParticleType.class:?]
	at mod.crystals.network.PacketSealFX$Handler.onMessage(PacketSealFX.java:61) ~[PacketSealFX$Handler.class:?]`Do I have an insufficient version of Java or what is the problem?
[latest.log](https://github.com/amadornes/ModJam5/files/1877126/latest.log)

**Comment by therealfarfetchd** [comment]
This should be fixed on the builds from Curse, but you can fix it by putting this https://farfetchd.duckdns.org/stuff/vec3f.jar in your mods folder.
